name: Multi-Branch Build Pipeline

on:
  push:
    branches:
      - main
      - develop
      - qa
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Based on Branch
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "ENV=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" =~ ^feature/ ]]; then
            echo "ENV=feature-testing" >> $GITHUB_ENV
          else
            echo "ENV=unknown" >> $GITHUB_ENV
          fi

      - name: Print Environment
        run: |
          echo "Running on branch: ${{ github.ref_name }}"
          echo "Environment: $ENV"

      - name: Build Application
        run: |
          echo "Building application for environment: $ENV"
          # Replace with actual build commands
          echo "Build completed."

      - name: Run Tests
        run: |
          echo "Running tests for environment: $ENV"
          # Replace with actual test commands
          echo "Tests completed."

      - name: Deploy to Production (Main Branch Only)
        if: github.ref_name == 'main'
        run: |
          echo "Deploying to Production Environment"
          # Add production deployment steps here
          echo "Deployment completed."
