name: Multi-Branch Build Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Based on Branch
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" =~ ^release/ ]]; then
            echo "ENV=pre-production" >> $GITHUB_ENV
          else
            echo "ENV=testing" >> $GITHUB_ENV
          fi

      - name: Print Environment
        run: |
          echo "Running on environment: $ENV"

      - name: Build Application
        run: |
          echo "Building branch: ${{ github.ref_name }}"
          echo "Environment: $ENV"
          # Replace with actual build commands
          echo "Build completed successfully."

      - name: Run Tests
        run: |
          echo "Running tests for environment: $ENV"
          # Replace with actual test commands
          echo "Tests passed successfully."

      - name: Deploy (Production Only)
        if: github.ref_name == 'main'
        run: |
          echo "Deploying to Production Environment"
          # Replace with actual deployment steps
          echo "Deployment completed successfully."
